version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"

    environment:
      - CHOKIDAR_USEPOLLING=true


  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"  # Backend jest dostępny na porcie 5000
    environment:
      - FLASK_RUN_HOST=0.0.0.0  # Flask będzie nasłuchiwał na wszystkich interfejsach
